"""add gender check constraint

Revision ID: 88d41d909b8b
Revises: 8b9f594423e5
Create Date: 2024-12-09 12:12:16.802951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d41d909b8b'
down_revision: Union[str, None] = '8b9f594423e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('chk_gender_male_female', 'customers', "gender IN ('male', 'female')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_gender_male_female', 'customers', type_='check')
    # ### end Alembic commands ###
