name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio

      # Run tests
      - name: Run tests
        env:
          PYTHONPATH: .
          DB_URL: "sqlite:///:memory:?check_same_thread=False"
          TEST_DB_URL: "sqlite:///:memory:?check_same_thread=False"
        run: |
          pytest -v --capture=no

  build-and-deploy:
    needs: setup-and-test
    runs-on: ubuntu-latest
    steps:
      # Explicitly check out code for the deployment job
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DigitalOcean
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
          DIGITALOCEAN_USERNAME: ${{ github.actor }}
        run: |
          echo "${DIGITALOCEAN_ACCESS_TOKEN}" | docker login registry.digitalocean.com -u "${DIGITALOCEAN_USERNAME}" --password-stdin

      - name: Build Docker image
        env:
          COMMIT_HASH: ${{ github.sha }}
        run: |
          docker build -t registry.digitalocean.com/devops-api/health-api:${COMMIT_HASH} -t registry.digitalocean.com/devops-api/health-api:latest .

      - name: Push Docker image to DigitalOcean
        env:
          COMMIT_HASH: ${{ github.sha }}
        run: |
          docker push --all-tags registry.digitalocean.com/devops-api/health-api

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Configure kubeconfig
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p $HOME/.kube
          echo "${KUBE_CONFIG_DATA}" > $HOME/.kube/config

      - name: Update Deployment with New Image
        env:
          COMMIT_HASH: ${{ github.sha }}
        run: |
          kubectl set image deployment/website website=registry.digitalocean.com/devops-api/health-api:${COMMIT_HASH} -n health-app-ns
